#!/usr/bin/env python3
"""duink.com 全站硬编码中文 → 英文(SSG 直接输出英文,JS 不干扰)
用法: python3 i18n-cn2en.py [项目src目录]
"""
import re, glob, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else '/data/www/duink.com/src'

# 中文 → 英文映射(国际网站用词;长句优先匹配)
MAP = [
    # 导航/全局
    ('返回 DeepSeek-Harness 插件市场首页', 'Back to DSH plugin marketplace home'),
    ('返回首页', 'Back to Home'),
    ('关于我们', 'About'),
    ('技能专区', 'Skills'),
    ('会员中心', 'Members'),
    ('收录申请', 'Submit'),
    ('宇宙手记', 'Journal'),
    ('值得插件', 'Worth Plugins'),
    ('站点特性', 'Site Features'),
    ('自动收录', 'Auto-discovery'),
    ('分类验证', 'Validation pipeline'),
    ('一键安装', 'One-click install'),
    ('浏览入口', 'Browse'),
    ('中文', '中文'),
    ('日本語', '日本語'),
    ('切换到浅色模式', 'Switch to light mode'),
    ('蓝色主题', 'Blue theme'),
    ('紫色主题', 'Purple theme'),
    ('查看项目源码', 'View source'),
    ('广告', 'Ad'),
    ('広告', 'Ad'),
    ('广告位', 'Ad Slot'),
    ('广告位预留 · 可配置', 'Ad placeholder — configurable'),
    # 首页
    ('综合推荐', 'Recommended'),
    ('个项目', 'projects'),
    ('展开全部分类', 'Expand all categories'),
    ('折叠分类', 'Collapse categories'),
    ('未知', 'Unknown'),
    ('今天', 'Today'),
    ('天前', 'days ago'),
    ('个月前', 'months ago'),
    ('年前', 'years ago'),
    ('最新手记轻量横条', 'Latest journal'),
    # 详情页
    ('等待处理', 'Pending'),
    ('正在执行', 'Running'),
    ('已通过', 'Passed'),
    ('未通过', 'Failed'),
    ('需要复核', 'Needs review'),
    ('安全复核', 'Security review'),
    ('不适用', 'N/A'),
    ('截图预览', 'Screenshot preview'),
    ('验证状态：', 'Verification: '),
    ('查看 ', 'View '),
    ('在本机 DSH 中安装 ', 'Install in local DSH: '),
    ('查看包含 ', 'Browse '),
    ('高', 'High'),
    ('无有效分类标签', 'No valid category tags'),
    ('已归档', 'Archived'),
    ('优秀', 'Excellent'),
    ('良好', 'Good'),
    ('一般', 'Average'),
    ('偏低', 'Low'),
    ('复制安装参考', 'Copy install reference'),
    ('该命令已通过安装计划安全校验，可由 DSH host 执行；验证状态仍不等同安全审计或官方背书。', 'This command passed the install-plan safety check and can be executed by a DSH host; verification status is not equivalent to a security audit or official endorsement.'),
    ('该命令来自 README 的明确安装特征，仅作为参考，不会由 DSH host 自动执行。', 'This command comes from an explicit install reference in the README and is provided for reference only — it is never auto-executed by a DSH host.'),
    ('⛔ 风险检出 · 不建议安装', '⛔ Risk detected — not recommended'),
    # reviews
    ('显示更多（', 'Show more ('),
    ('收起', 'Collapse'),
    ('推荐', 'Recommended'),
    ('硬编码密钥', 'Hardcoded secrets'),
    ('（共 ', ' ('),
    ('项检出）', ' findings)'),
    ('：值得装吗？', ': Worth installing?'),
    ('分', '/10'),
    ('风险', 'Risky'),
    ('项检出', 'findings'),
    ('按评分排序 · 数据由评测引擎自动生成', 'Sorted by score — data auto-generated by the review engine'),
    # journal
    ('科技', 'Tech'),
    ('财经', 'Finance'),
    ('安全', 'Security'),
    ('书籍', 'Books'),
    ('日历', 'Calendar'),
    ('专栏分类', 'Columns'),
    ('全部', 'All'),
    # news
    ('天', 'days'),
    ('条要闻', 'headlines'),
    ('每日更新', 'Daily'),
    ('情报分类', 'Categories'),
    ('条', 'items'),
    # skills
    ('排序', 'Sort'),
    ('没有找到匹配的技能，换个关键词试试。', 'No matching skills found. Try a different keyword.'),
    # submit
    ('本市场自动收录同时打上 dsh-plugin 与 deepseek-harness 话题的公开仓库，无需人工审核。', 'This marketplace automatically indexes public repositories tagged with both dsh-plugin and deepseek-harness — no manual review needed.'),
    ('在仓库 Settings → Topics 中同时添加 dsh-plugin 和 deepseek-harness 两个', 'Add both dsh-plugin and deepseek-harness to Settings → Topics of your repository.'),
    ('市场每 30 分钟自动同步一次 GitHub 数据，收录后无需任何人工操作。', 'The marketplace syncs GitHub data every 30 minutes — nothing else needed after indexing.'),
    ('在首页搜索你的仓库名即可确认收录结果。', 'Search your repository name on the homepage to confirm indexing.'),
    ('如果仓库不便打话题（如私有仓库或非 GitHub 托管），可通过 GitHub Issue 提交申请。', 'If your repository cannot use topics (private or non-GitHub hosted), submit a request via GitHub Issue.'),
    ('需要同时包含 dsh-plugin 与 deepseek-harness 两个话题；归档仓库、Fork 和被识别为宿主应', 'Must include both dsh-plugin and deepseek-harness topics; archived repos, forks, and host applications are'),
    ('你的项目会出现在市场目录中，获得分类、标签、搜索与验证状态展示，并可通过安装命令一键安装。', 'Your project will appear in the marketplace with category, tags, search, verification status, and a one-click install command.'),
    # topics
    ('标签 · DSH 插件市场', ' · DSH Plugin Marketplace'),
    ('浏览 GitHub Topic 为 ', 'Browse GitHub Topic: '),
    # about
    ('自动收录、分类并验证 DeepSeek Harness 生态的插件、技能与应用，帮助开发者更快发现和使用优秀的 DSH', 'Auto-indexes, categorizes, and verifies plugins, skills, and apps in the DeepSeek Harness ecosystem — helping developers discover and use the best DSH'),
    ('所有项目数据来自 GitHub 公开仓库元数据，仅做索引与整理，不执行第三方代码。收录不代表审核、兼容性或安全性背书，安', 'All project data comes from public GitHub repository metadata — index only, never executes third-party code. Indexing does not imply audit, compatibility, or security endorsement. Sec'),
    ('让 DeepSeek Harness 生态的每一个插件、技能与应用都能被轻松发现。我们相信「万物皆插件」，也相信好的工具', 'Every plugin, skill, and app in the DeepSeek Harness ecosystem should be easy to discover. We believe everything is a plugin — and that great tools'),
    ('插件收录申请、合作建议、问题反馈，欢迎通过邮件与我们联系。', 'Plugin submissions, partnership ideas, and feedback — reach us by email.'),
    # members
    ('加入 DSH UNIVERSE 会员，解锁金色徽章、优先验证通道与内测资格，与生态共同成长。', 'Join DSH UNIVERSE membership to unlock the gold badge, priority verification, and beta access — grow with the ecosystem.'),
    ('会员权益', 'Membership benefits'),
    ('普通会员', 'Free'),
    ('邮箱验证', 'Email verification'),
    # 404
    ('这个页面还没有内容，先去看看插件市场吧。', 'This page has no content yet — browse the plugin marketplace instead.'),
    # Hero/Features 描述
    ('DSH UNIVERSE 主视觉', 'DSH UNIVERSE'),
    ('收录 DeepSeek Harness 生态的插件、技能与应用，一个宇宙装下所有可能性。', 'Plugins, skills, and apps for the DeepSeek Harness ecosystem — one universe, every possibility.'),
    ('GitHub 双话题仓库每 30 分钟自动同步，生态新增即收录，不遗漏。', 'Repositories with both GitHub topics sync every 30 minutes — nothing new is missed.'),
    ('结构检查、实机验证、安全复核——多阶段验证体系，拒绝僵尸仓库。', 'Structure checks, live verification, security review — a multi-stage pipeline that rejects zombie repos.'),
    ('DSH Web 插件包，打开 Harness 即装即用，零配置上手。', 'DSH web plugin bundle — install with one click in Harness, zero config.'),
    ('生态增长趋势', 'Ecosystem growth'),
    ('插件数量增长曲线', 'Plugin count growth'),
    ('首个', 'first'),
    ('今日', 'Today'),
]

def apply(text):
    for cn, en in MAP:
        if cn in text:
            text = text.replace(cn, en)
    return text

total_files, total_repl = 0, 0
for f in glob.glob(SRC + '/**/*.astro', recursive=True):
    lines = open(f, encoding='utf-8').read().split('\n')
    changed = 0
    for i, ln in enumerate(lines):
        s = ln.strip()
        if '<!--' in s or s.startswith('//') or s.startswith('/*') or s.startswith('*'):
            continue
        new = apply(ln)
        if new != ln:
            lines[i] = new
            changed += 1
    if changed:
        open(f, 'w', encoding='utf-8').write('\n'.join(lines))
        total_files += 1
        total_repl += changed
        print(f"  {f.replace(SRC + '/', '')}: {changed} 行已英文化")
print(f"\n完成: {total_files} 个文件, {total_repl} 行替换")
